config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  resources :user, only: [:show]
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  } 
  
  resources :footprints, only: [:show, :edit]
  resources :product do
    resources :footprints, only: [:new, :create]
  end

  namespace :admin do
    root :to=> 'admin#index'
    resources :users , except: [:new , :create, :edit]
    resources :products 
    resources :foot_prints , except: [:edit, :new, :update]
  end

resources :contact , only: [:index]
resources :methodologie , only: [:index]

  # get "*path" => redirect("/")# A decommenter vers la fin

end

app/models/product.rb
class Product < ApplicationRecord
  validates :type_id, presence: true
  validates :brand_id, presence: true
  validates :warehouse_id, presence: true
  has_many :footprints
  has_many :users, through: :footprints
  belongs_to :type

  belongs_to :warehouse

  belongs_to :brand


  def tx_total
    brand.ratio.carbon_print_for_brand * type.value.carbon_print
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authorize_admin

  def index
    @product = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def create
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      
    end
  end

  def edit
  end

  def update
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController

  def index
    @product= Product.all
  end

  def show
    @product = Product.find(params[:id])
      total = @product.tx_total
      total.round(2)


  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/product/index.html.erb
<br>
<br>
<br>
<div class="container">
  <div class="card text-center d-flex">
    <%@product.each do |item|%>
        <div class="card-header">
          <%= item.title %>
        </div>
        <div class="card-body">
                <h5 class="card-title"><%= item.description  %></h5>
                <%if item.price == nil %>
                <p>le prix n'est pas renseigné</p>
                <%else%>
                <p class="card-text"><%= item.price %></p>
                <%end%>
          <%=link_to "voir plus", product_path(item),class:"btn btn-info" %>
        </div>
        <hr>
  <%end%>
  </div>
</div>

app/views/product/show.html.erb
 <img class="card-img" src="/../assets/img/bg19.jpg" alt="Card image">


<div class="wrapper">
        <div class="page-header-mini" filter-color="orange">
            <div class="page-header-image" data-parallax="true";>
            </div>
        </div>
        <div class="section">
            <div class="container">
                <div class="row">
                    <div class="col-md-5" style="margin-top: -20%">
                        
                            <div class="carousel-inner" role="listbox">
                                <div class="carousel-item active">
                                    <img class="d-block img-raised" src="/../assets/img/visuel-non-disponible.jpg">
                           
                        </div>
                    </div>
                        
                      <% if user_signed_in? %>
                            <div id="new-test" >
                                <%= link_to "Calculez l'empreinte carbone de la livraison", new_product_footprint_path(product_id: @product.id),
                                 remote: true %>
                             </div>
               
                            
                            <% else %>
                            <p class="btn"><%= link_to "connectez vous pour calculer l'empreinte de la livraison", new_user_session_path %></p>
                        <%end%>
                    
                    </div>
                        
                    
                    <div class="col-md-6 ml-auto mr-auto" style="margin-top: -19%">
                        <h2 class="title" style="color: white;font-size: 300%"> <%= @product.title.capitalize %> </h2>
                        <h5 class="category" style="color: white;font-size: 200%"> <%= @product.type.name %></h5>
                        
                        <div id="accordion" role="tablist" aria-multiselectable="true" class="card-collapse">
                            <div class="card card-plain">
                                <div class="card-header" role="tab" id="headingOne">

                                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">

                                        <%= @product.tx_total %> de kg de Co2 emit

                                       

                                    </a>
                                </div>
                                
                            </div>

                        

                    </div>
                </div>
            </div>
        </div>

    </div>
</div>