config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  resources :user, only: [:show]
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  } 
  
  resources :footprints, only: [:show, :edit]
  resources :product do
    resources :footprints, only: [:new, :create]
  end

  namespace :admin do
    root :to=> 'admin#index'
    resources :users , except: [:new , :create, :edit]
    resources :products 
    resources :foot_prints , except: [:edit, :new, :update]
  end

resources :contact , only: [:index]
resources :methodologie , only: [:index]

  # get "*path" => redirect("/")# A decommenter vers la fin

end

app/models/product.rb
class Product < ApplicationRecord
  validates :type_id, presence: true
  validates :brand_id, presence: true
  validates :warehouse_id, presence: true
  has_many :footprints
  has_many :users, through: :footprints
  belongs_to :type

  belongs_to :warehouse

  belongs_to :brand


  def tx_total
    brand.ratio.carbon_print_for_brand * type.value.carbon_print
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authorize_admin

  def index
    @product = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def create
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      
    end
  end

  def edit
  end

  def update
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController

  def index
    @product= Product.all
  end

  def show
    @product = Product.find(params[:id])
      total = @product.tx_total
      total.round(2)


  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/admin/products/index.html.erb
<br>
<br>
<br>
<br>
<br>
<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Titre</th>
      <th scope="col">Catégorie</th>
      <th scope="col">Marque</th>
      <th scope="col">Plus</th>
      <th scope="col">Supprimer</th>


    </tr>
  </thead>
  <tbody>
    <%@product.each do |pro|%>
    <tr>
      <td><%= pro.id %></td>
      <td><%= pro.title %></td>
      <td><%= pro.type.name%></td>
      <td><%= pro.brand.name %></td>
      <td><%= link_to "more", admin_product_path(pro.id) %></td>
      <td><%= link_to "Delete", admin_product_path(pro.id),data: { :confirm => "Are you sure?"}, :method => :delete %></td>

    </tr>
      <%end%>
  </tbody>
</table>

app/views/admin/products/show.html.erb
<div class="wrapper">
  <div class="section">
    <div class="container">
      <div class="row">
        <div class="col-md-5" style="margin-top: -10%">
          <div id="productCarousel" class="carousel slide" data-ride="carousel" data-interval="8000">
            <ol class="carousel-indicators">
              <li data-target="#productCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#productCarousel" data-slide-to="1"></li>
              <li data-target="#productCarousel" data-slide-to="2"></li>
              <li data-target="#productCarousel" data-slide-to="3"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
              <div class="carousel-item active">
                <img class="d-block img-raised" src="https://images.pexels.com/photos/193004/pexels-photo-193004.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" alt="First slide">
              </div>
              <div class="carousel-item">
                <img class="d-block img-raised" src="../assets/img/pp-2.jpg" alt="Second slide">
              </div>
              <div class="carousel-item">
                <img class="d-block img-raised" src="../assets/img/pp-3.jpg" alt="Third slide">
              </div>
              <div class="carousel-item">
                <img class="d-block img-raised" src="../assets/img/pp-4.jpg" alt="Third slide">
              </div>
            </div>
            <a class="carousel-control-prev" href="#productCarousel" role="button" data-slide="prev">
              <button type="button" class="btn btn-primary btn-icon btn-round btn-sm" name="button">
                <i class="now-ui-icons arrows-1_minimal-left"></i>
              </button>
            </a>

            <a class="carousel-control-next" href="#productCarousel" role="button" data-slide="next">
              <button type="button" class="btn btn-primary btn-icon btn-round btn-sm" name="button">
                <i class="now-ui-icons arrows-1_minimal-right"></i>
              </button>
            </a>
          </div>
          <p class="blockquote blockquote-primary">
            "And thank you for turning my personal jean jacket into a couture piece. Wear yours with mirrored sunglasses on vacation."
            <br>
            <br>
            <small>Kanye West</small>
          </p>
        </div>
        <div class="col-md-6 ml-auto mr-auto">
          <h2 class="title"> <%= @product.title.capitalize %> </h2>
          <h5 class="category">Slim-Fit Leather Biker Jacket</h5>
          <%if @product.price == nil%>
            <h5>Prix non renseigné</h5>
            <%else%>
              <h2 class="main-price"><%= @product.price %> €</h2>
              <%end%>
                <div id="accordion" role="tablist" aria-multiselectable="true" class="card-collapse">
                  <div class="card card-plain">
                    <div class="card-header" role="tab" id="headingOne">
                      <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
  Description
  <i class="now-ui-icons arrows-1_minimal-down"></i>
  </a>
                    </div>
                    <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
                      <div class="card-body">
                        <%= @product.description %>
                      </div>
                    </div>
                  </div>

                  <div id="new-test" class="row justify-content-end">
                    <%= link_to "Calculer l'empreinte carbon", new_product_footprint_path(product_id: @product.id), remote: true, :style=> 'color:#FFFFFF;', :class => 'btn btn-secondary mr-7'%>
                  </div>
                  <div class="btn">
                    <%= link_to "Delete", admin_product_path(@product.id), :confirm => "Are you sure?", :method => :delete %>
                  </div>

                </div>
        </div>
      </div>
    </div>
  </div>
</div>