config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  resources :user, only: [:show]
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  } 
  
  resources :footprints, only: [:show, :edit]
  resources :product do
    resources :footprints, only: [:new, :create]
  end

  namespace :admin do
    root :to=> 'admin#index'
    resources :users , except: [:new , :create, :edit]
    resources :products 
    resources :foot_prints , except: [:edit, :new, :update]
  end

resources :contact , only: [:index]
resources :methodologie , only: [:index]

  # get "*path" => redirect("/")# A decommenter vers la fin

end

app/models/footprint.rb
class Footprint < ApplicationRecord
  validates :zip_code, presence: true
  validates :user_id, presence: true
  validates :product_id, presence: true

  belongs_to :user
  belongs_to :product
  
  geocoded_by :location
  after_validation :geocode #if: :location_changed?

  def location
    [town, country].compact.join(", ")
  end

  def location_changed?
    town.changed? || country.changed?
  end
  
end

app/controllers/admin/foot_prints_controller.rb
class Admin::FootPrintsController < ApplicationController
  before_action :authorize_admin

  def index
    @foot_print = Footprint.all
  end

  def show
    @foot_print = Footprint.find(params[:id])
  end


  def destroy
    @foot_print = Footprint.find(params[:id])
    if @foot_print.destroy
        flash[:success]="Test deleted"
        redirect_back(fallback_location: admin_foot_print_path)
    end
  end

end

app/controllers/footprints_controller.rb
class FootprintsController < ApplicationController
  before_action :set_footprint, only: [:show, :edit, :update, :destroy]

    # GET /footprints
    # GET /footprints.json
    def index
      @footprints = Footprint.all
    end

    # GET /footprints/1
    # GET /footprints/1.json
    def show
        # @distance = @footprint.product.distance_to(@footprint).round.to_f * 1.609
        @footprint = Footprint.find(params[:id])
        url_city_product = "https://api.airvisual.com/v2/nearest_city?lat=#{@footprint.latitude}&lon=#{@footprint.longitude}&key=BbFES4LurEehNo6PR"
        @response_product = open(url_city_product).read
        @res_product = JSON.parse(@response_product).with_indifferent_access
      puts  @res_product[:data][:current][:pollution][:mainus]
            @aqius_product    = @res_product[:data][:current][:pollution][:aqius]
            @city_product     = @res_product[:data][:city]
            @country_product  = @res_product[:data][:country]
            @state_product    = @res_product[:data][:state]
        puts "*"*90
        puts "*"*90
    end

    # GET /footprints/new
    def new
      @footprint = Footprint.new
      @product = Product.find(params[:product_id])
    end

    # GET /footprints/1/edit
    def edit
    end

    # POST /footprints
    # POST /footprints.json
    def create
      @footprint = Footprint.new(footprint_params)
      @footprint.user_id = current_user.id
      @footprint.geocode
      @warehouse = Warehouse.all
      @near_city = @warehouse.near(@footprint.town)
      @distance = @footprint.product.warehouse.distance_to(@footprint).round.to_f * 1.609
      @co_by_km = @distance / 2.50
      @co_by_km
      
      @result_before_float = @footprint.product.tx_total + @co_by_km

      @footprint.result = (@result_before_float.to_f).round(2)

      respond_to do |format|
        if @footprint.save
          format.js
          format.html { redirect_to @footprint, notice: 'Foot print was successfully created.' }
        else
          format.html { render :new }
        end
      end

    end

    # PATCH/PUT /footprints/1
    # PATCH/PUT /footprints/1.json
    def update
      respond_to do |format|
        if @footprint.update(footprint_params)
          format.html { redirect_to @footprint, notice: 'Foot print was successfully updated.' }
          format.json { render :show, status: :ok, location: @footprint }
        else
          format.html { render :edit }
          format.json { render json: @footprint.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /footprints/1
    # DELETE /footprints/1.json


    private
      # Use callbacks to share common setup or constraints between actions.
      def set_footprint
        @footprint = Footprint.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def footprint_params
        params.require(:footprint).permit(:delivery_address, :zip_code, :town, :country, :latitude, :longitude, :result, :user_id, :product_id)
      end
  end

  def a_voir

    if user_signed_in?
      url_city_user    = "https://api.airvisual.com/v2/nearest_city?lat=#{current_user.latitude}&lon=#{current_user.longitude}&key=BbFES4LurEehNo6PR"
      puts @response = open(url).read
      puts current_user.latitude
      # puts "*"*90
      # puts @response.to_json
      @res = JSON.parse(@response).with_indifferent_access
        @aqius = @res[:data][:current][:pollution][:aqius]
        @res[:data][:current][:pollution][:mainus]
        @city = @res[:data][:city]
        @country = @res[:data][:country]
        @state = @res[:data][:state]
        puts "*"*90
    end

end

app/helpers/admin/foot_prints_helper.rb
module Admin::FootPrintsHelper
end

app/helpers/footprints_helper.rb
module FootprintsHelper
end

app/views/footprints/_footprint.html.erb
<!-- <script>

  let doNothing = document.getElementById("do-nothing")
  doNothing.addEventListener("mouseover", function(){
    console.log("owowowo")
  })
</script> -->
<div class="card  col-lg-12">
<div class="container" id="not-clickable">

<p id="notice"><%= notice %></p>

<h4 style="color:green;">
  <strong>Resultat:</strong>
  <%= footprint.result %> CO2
</h4>

<p>
  <strong>Utilisateur:</strong>
  <%= footprint.user.first_name %><%= footprint.user.last_name %>
</p>

<p>
  <strong>Produit:</strong>
  <%= footprint.product.title %>
</p>

<p>
  <strong>Adresse de livraison:</strong>
  <%= footprint.delivery_address %>
</p>

<p>
  <strong>Code postal:</strong>
  <%= footprint.zip_code %>
</p>

<p>
  <strong>Ville:</strong>
  <%= footprint.town %>
</p>

<p>
  <strong>Pays:</strong>
  <%= footprint.country %>
</p>








<%= link_to 'Edit', edit_footprint_path(footprint.id) %> 
<%# <%= link_to 'Back', foot_prints_path %> 

<br>
</div>

</div>
<br>
</center>
<div id='map'></div>



<%= javascript_tag do %>
console.log("<%= @footprint.town %>")
console.log("<%= @footprint.product %>")

var ENV = {
 MAPBOX_API: '<%= ENV['MAPBOX_API'] %>',
}
mapboxgl.accessToken =ENV['MAPBOX_API']

var map = new mapboxgl.Map({
 container: 'map', // container id
 style: 'mapbox://styles/mapbox/navigation-preview-day-v4', // stylesheet location
 center: [2.56123,48.817038], // starting position
 zoom: 3 // starting zoom
});

var route = {
 type: 'FeatureCollection',
 features: [{
   type: 'Feature',
   geometry: {
     type: 'Point',
     coordinates: [<%= @footprint.product.warehouse.longitude %>,<%= @footprint.product.warehouse.latitude %>]
   },
   properties: {
     title: '<%= @footprint.product.title %>',
     description: '<%= @footprint.product.title %>,<%= @footprint.product.title %>'
   }
 },
 {
   type: 'Feature',
   geometry: {
     type: 'Point',
     coordinates: [<%= @footprint.longitude %>,<%= @footprint.latitude %>]
   },
   properties: {
     title: '<%= @footprint.user.first_name %>',
     description: '<%= @footprint.town %>,<%= @footprint.country %>'
   }
 }]
};


// add markers to map
route.features.forEach(function(marker) {

 // create a HTML element for each feature
 var el = document.createElement('div');
 el.className = 'marker';

 new mapboxgl.Marker(el)

 .setLngLat(marker.geometry.coordinates)
 .setPopup(new mapboxgl.Popup({ offset: 25 }) // add popups
   .setHTML('<h3>' + marker.properties.title + '</h3><p>' + marker.properties.description + '</p>')
   )
   .addTo(map);
});


var directions = new MapboxDirections({
 accessToken: ENV['MAPBOX_API'],
 unit: 'metric',
 profile: 'mapbox/driving',

});
 directions.setOrigin([<%= @footprint.product.warehouse.longitude %>,<%= @footprint.product.warehouse.latitude %>])
 directions.addWaypoint(0,[<%= @footprint.product.warehouse.longitude + 0.1 %>,<%= @footprint.product.warehouse.latitude + 0.02 %>])
 directions.setDestination([<%= @footprint.longitude %>,<%= @footprint.latitude %>])



// add to your mapboxgl map
map.addControl(directions, 'top-left');
map.addControl(new mapboxgl.NavigationControl());

<%end%>


   <% @foot_distance=  footprint.distance_to(footprint.product.warehouse)*1.609 %>

<h1>
   <%= @foot_distance.to_i %>km
</h1>


<script type="text/javascript">
let notClickable = document.getElementById("not-clickable")
notClickable.style.pointerEvents="none";
console.log("not-clickable")
</script>

app/views/footprints/_form.html.erb
<div class="form-group">

  <%= form_for [@product , @footprint], remote: true do |form| %>

      <% if footprint.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(footprint.errors.count, "error") %> erreur de sauvegarde</h2>
              <ul>
                <% footprint.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              </ul>
                <% end %>
          </div>
      <% end %>


  <%= form.hidden_field :product_id, value: @product.id %>

    <div class="form-control">
      <%= form.label :delivery_address %>
      <%= form.text_field :delivery_address , class:"form-control", placeholder: "Votre Adresse" %><br />
    </div>


    <div class="form-control">
      <%= form.label :zip_code %>
      <%= form.text_field :zip_code , class:"form-control", placeholder: "Votre code Postal" %><br />
    </div>


    <div class="form-control">
      <%= form.label :town %>
      <%= form.text_field :town , class:"form-control", placeholder: "Votre Ville" %><br />
    </div>

    <%= form.hidden_field :country , value:"France"%><br />

    <button type="form.submit" class="btn btn-primary btn-round" >Let's go</button>
  <% end %>

</div>

app/views/footprints/create.js.erb
$('#new-test form').remove();
$('#new-test a').show();
$('#new-test a').html(" <%= j render @footprint %>")

app/views/footprints/edit.html.erb
<h1>Editing Footprint</h1>

<%= render 'form', footprint: @footprint %>

<%= link_to 'Show', @footprint %> |
<%= link_to 'Back', footprints_path %>

app/views/footprints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foot Prints</h1>

<table>
  <thead>
    <tr>
      <th>Adresse de livraison</th>
      <th>Code postal</th>
      <th>Ville</th>
      <th>Pays</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Resulta</th>
      <th>Utilisateur</th>
      <th>Produit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @footprints.each do |footprint| %>
      <tr>
        <td><%= footprint.delivery_address %></td>
        <td><%= footprint.zip_code %></td>
        <td><%= footprint.town %></td>
        <td><%= footprint.country %></td>
        <td><%= footprint.latitude %></td>
        <td><%= footprint.longitude %></td>
        <td><%= footprint.result %></td>
        <td><%= footprint.user_id %></td>
        <td><%= footprint.product_id %></td>
        <td><%= link_to 'Show', footprint %></td>
        <td><%= link_to 'Edit', edit_footprint_path(footprint) %></td>
        <td><%= link_to 'Destroy', footprint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foot Print', new_footprint_path %>

app/views/footprints/new.html.erb
<div class="wrapper">
        <div class="page-header page-header-small">
            <div class="page-header-image" data-parallax="true" style="background-image: url('../assets/img/bg37.jpg') ;">
            </div>
            <div class="content-center">
                <div class="row">
                    <div class="col-md-8 ml-auto mr-auto">
                        <h1 class="title">Nouveau Foot Print</h1>
                    </div>
                </div>
            </div>
        </div>
        <div class="main">
            <div class="pricing-4">
                <div class="container">

<center>
<%= render 'form', footprint: @footprint %>


<a class="btn btn-primary btn-round" href="/" > Retour </a>
</center>





</div>

app/views/footprints/new.js.erb
$('#new-test a').hide().parent().append(" <%= j render 'form', footprint: @footprint %>");

app/views/footprints/show.html.erb
<div class="wrapper">
        <div class="page-header page-header-mini">
            <div class="page-header-image" data-parallax="true" style="background-image: url('../assets/img/pp-cov.jpg') ;">
            </div>
        </div>
        <div class="section">
            <div class="container">
                <div class="row">
                    <div class="col-md-5" style="margin-top: -10%">
                        <div id="productCarousel" class="carousel slide" data-ride="carousel" data-interval="8000">
                            <ol class="carousel-indicators">
                                <li data-target="#productCarousel" data-slide-to="0" class="active"></li>
                                <li data-target="#productCarousel" data-slide-to="1"></li>
                                <li data-target="#productCarousel" data-slide-to="2"></li>
                                <li data-target="#productCarousel" data-slide-to="3"></li>
                            </ol>
                            <div class="carousel-inner" role="listbox">
                                <div class="carousel-item active">
                                    <img class="d-block img-raised" src="../assets/img/pp-1.jpg" alt="First slide">
                                </div>
                                <div class="carousel-item">
                                    <img class="d-block img-raised" src="../assets/img/pp-2.jpg" alt="Second slide">
                                </div>
                                <div class="carousel-item">
                                    <img class="d-block img-raised" src="../assets/img/pp-3.jpg" alt="Third slide">
                                </div>
                                <div class="carousel-item">
                                    <img class="d-block img-raised" src="../assets/img/pp-4.jpg" alt="Third slide">
                                </div>
                            </div>
                            <a class="carousel-control-prev" href="#productCarousel" role="button" data-slide="prev">
                                <button type="button" class="btn btn-primary btn-icon btn-round btn-sm" name="button">
                                    <i class="now-ui-icons arrows-1_minimal-left"></i>
                                </button>
                            </a>
                            <a class="carousel-control-next" href="#productCarousel" role="button" data-slide="next">
                                <button type="button" class="btn btn-primary btn-icon btn-round btn-sm" name="button">
                                    <i class="now-ui-icons arrows-1_minimal-right"></i>
                                </button>
                            </a>
                        </div>
                        <p class="blockquote blockquote-primary">
                            "And thank you for turning my personal jean jacket into a couture piece. Wear yours with mirrored sunglasses on vacation."
                            <br>
                            <br>
                            <small>Kanye West</small>
                        </p>
                    </div>
                    <div class="col-md-6 ml-auto mr-auto">
                        <h2 class="title"> <%= @footprint.product.title %> </h2>
                        <h5 class="category"><%= @footprint.product.type.name %></h5>
                        <% if @footprint.product.price == nil %>
                        <h3> Prix n'est pas renseigné</h3>
                        <%else%>
                          <h2 class="main-price"><%= @footprint.product.price %></h2>
                        <%end%>
                        <div id="accordion" role="tablist" aria-multiselectable="true" class="card-collapse">
                            <div class="card card-plain">
                                <div class="card-header" role="tab" id="headingOne">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                        Description
                                        <i class="now-ui-icons arrows-1_minimal-down"></i>
                                    </a>
                                </div>
                                <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
                                    <div class="card-body">
                                        <p>Eres' daring 'Grigri Fortune' swimsuit has the fit and coverage of a bikini in a one-piece silhouette. This fuchsia style is crafted from the label's sculpting peau douce fabric and has flattering cutouts through the torso and back. Wear yours with mirrored sunglasses on vacation.</p>
                                    </div>
                                </div>
                            </div>
                            <!-- <div class="card card-plain"> -->
                                <!-- <div class="card-header" role="tab" id="headingTwo">
                                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                        Designer Information
                                        <i class="now-ui-icons arrows-1_minimal-down"></i>
                                    </a>
                                </div> -->
                                <!-- <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo">
                                    <div class="card-body">
                                        <p>An infusion of West Coast cool and New York attitude, Rebecca Minkoff is synonymous with It girl style. Minkoff burst on the fashion scene with her best-selling 'Morning After Bag' and later expanded her offering with the Rebecca Minkoff Collection - a range of luxe city staples with a "downtown romantic" theme.</p>
                                    </div>
                                </div> -->
                            <!-- </div> -->
<p id="notice"><%= notice %></p>

<p>
  <strong>Delivery address:</strong>
  <%= @footprint.delivery_address %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @footprint.zip_code %>
</p>

<p>
  <strong>Town:</strong>
  <%= @footprint.town %>
</p>

<p>
  <strong>Country:</strong>
  <%= @footprint.country %>
</p>

<% @foot_distance = @footprint.distance_to(@footprint.product.warehouse)*1.609 %>
<p>
  <strong>Distance:</strong>
  <%= @foot_distance.to_i %>km
</p>


<p>
  <strong>Latitude:</strong>
  <%= @footprint.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @footprint.longitude %>
</p>

<p>
  <strong>Result:</strong>
  <%= @footprint.result %>
</p>

<p>
  <strong>User:</strong>
  <%= @footprint.user_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @footprint.product_id %>
</p>





<%= link_to 'Edit', edit_footprint_path(@footprint.id) %> |

<br>
<hr>
<h3>Information de la ville de produit</h3>
<h6><%= "country: #{@country_product}"%></h6><br>
<h6><%= "City: #{@city_product}" %></h6><br>
<h6><%= "State: #{@state_product}"%></h6><br>
<h6><%= "Air Quality Index: #{@aqius_product} "%></h6>

<div class="card text-center">

  <div class="progress" >
    <% if @aqius_product <= 50 %>
    <div class="progress-bar bg-success"  style="width:100%"">
      Good
    </div>
    <% elsif  @aqius_product > 51 && @aqius_product <= 100 %>
    <div class="progress-bar bg-warning" style="width:100%">
      Moderate
    </div>
    <% elsif  @aqius_product >101 %>
    <div class="progress-bar bg-danger" style="width:100%" >
      Unhealthy for Sensitive Groups
    </div>
    <h4>Veuillez connecter pour voir la qualité de l'air de votre ville<h4>
  <% end %>
  </div>
</div>
<hr>
<div id='map'></div>
<div id='menu'>
<%# Switch layer %>
<input id='basic' type='radio' name='rtoggle' value='basic' checked='checked'>
<label for='basic'>basic</label>
<input id='streets' type='radio' name='rtoggle' value='streets'>
<label for='streets'>streets</label>
<input id='bright' type='radio' name='rtoggle' value='bright'>
<label for='bright'>bright</label>
<input id='light' type='radio' name='rtoggle' value='light'>
<label for='light'>light</label>
<input id='dark' type='radio' name='rtoggle' value='dark'>
<label for='dark'>dark</label>
<input id='satellite' type='radio' name='rtoggle' value='satellite'>
<label for='satellite'>satellite</label>
</div>


<%= javascript_tag do %>

var ENV = {
 MAPBOX_API: '<%= ENV['MAPBOX_API'] %>'
}
mapboxgl.accessToken =ENV['MAPBOX_API']

<%# switch layer: next 2 line %>
var layerList = document.getElementById('menu');
var inputs = layerList.getElementsByTagName('input');

var map = new mapboxgl.Map({
 container: 'map', // container id
 style: 'mapbox://styles/mapbox/navigation-preview-day-v4', // stylesheet location
 center: [2.56123,48.817038], // starting position
 zoom: 3 // starting zoom
});

var route = {
 type: 'FeatureCollection',
 features: [{
   type: 'Feature',
   geometry: {
     type: 'Point',
     coordinates: [<%= @footprint.product.warehouse.longitude %>,<%= @footprint.product.warehouse.latitude %>]
   },
   properties: {
     title: '<%= @footprint.product.title %>',
     description: '<%= @footprint.product.title %>,<%= @footprint.product.type.name %>'
   }
 },
 {
   type: 'Feature',
   geometry: {
     type: 'Point',
     coordinates: [<%= @footprint.longitude %>,<%= @footprint.latitude %>]
   },
   properties: {
     title: '<%= @footprint.user.first_name %>',
     description: '<%= @footprint.town %>,<%= @footprint.country %>'
   }
 }]
};


// add markers to map
route.features.forEach(function(marker) {

 // create a HTML element for each feature
 var el = document.createElement('div');
 el.className = 'marker';

 new mapboxgl.Marker(el)

 .setLngLat(marker.geometry.coordinates)
 .setPopup(new mapboxgl.Popup({ offset: 25 }) // add popups
   .setHTML('<h3>' + marker.properties.title + '</h3><p>' + marker.properties.description + '</p>')
   )
   .addTo(map);
});


var directions = new MapboxDirections({
 accessToken: ENV['MAPBOX_API'],
 unit: 'metric',
 profile: 'mapbox/driving',

  container:'directions', // Specify an element thats not the map container.
  // UI controls
  controls: {
    inputs: false,
    instructions: true
  }

});
 directions.setOrigin([<%= @footprint.product.warehouse.longitude %>,<%= @footprint.product.warehouse.latitude %>])
 directions.addWaypoint(0,[<%= @footprint.product.warehouse.longitude + 0.1 %>,<%= @footprint.product.warehouse.latitude + 0.02 %>])
 directions.setDestination([<%= @footprint.longitude %>,<%= @footprint.latitude %>])



// add to your mapboxgl map
map.addControl(directions, 'top-left');
map.addControl(new mapboxgl.NavigationControl());

//Switch layer until the loop
function switchLayer(layer) {
var layerId = layer.target.id;
map.setStyle('mapbox://styles/mapbox/' + layerId + '-v9');
}

for (var i = 0; i < inputs.length; i++) {
inputs[i].onclick = switchLayer;
}

let hideWhenMouseover =document.querySelector('#map > div.mapboxgl-control-container > div.mapboxgl-ctrl-top-left > div > div')
	hideWhenMouseover.addEventListener("mouseover", function(){
      setInterval(function(){
      hideWhenMouseover.style.visibility = "hidden"
    },3000)
  });
<%end%>


</div>
</div></div></div></div></div>