config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  resources :user, only: [:show]
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  } 
  
  resources :footprints, only: [:show, :edit]
  resources :product do
    resources :footprints, only: [:new, :create]
  end

  namespace :admin do
    root :to=> 'admin#index'
    resources :users , except: [:new , :create, :edit]
    resources :products 
    resources :foot_prints , except: [:edit, :new, :update]
  end

resources :contact , only: [:index]
resources :methodologie , only: [:index]

  # get "*path" => redirect("/")# A decommenter vers la fin

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord

  belongs_to :ratio
  
end

app/models/footprint.rb
class Footprint < ApplicationRecord
  validates :zip_code, presence: true
  validates :user_id, presence: true
  validates :product_id, presence: true

  belongs_to :user
  belongs_to :product
  
  geocoded_by :location
  after_validation :geocode #if: :location_changed?

  def location
    [town, country].compact.join(", ")
  end

  def location_changed?
    town.changed? || country.changed?
  end
  
end

app/models/product.rb
class Product < ApplicationRecord
  validates :type_id, presence: true
  validates :brand_id, presence: true
  validates :warehouse_id, presence: true
  has_many :footprints
  has_many :users, through: :footprints
  belongs_to :type

  belongs_to :warehouse

  belongs_to :brand


  def tx_total
    brand.ratio.carbon_print_for_brand * type.value.carbon_print
  end

end

app/models/ratio.rb
class Ratio < ApplicationRecord

  has_one :brand
  
end

app/models/type.rb
class Type < ApplicationRecord

  has_many :products
  belongs_to :value

end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true, length: { minimum: 3 }

  validates :email,
   presence: true,
   uniqueness: true,
   format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }

  validates :password, length: { in: 6..20 }


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[facebook]


  has_many :footprints
  has_many :products, through: :footprints

  after_create :welcome_send

    def welcome_send
      UserMailer.welcome_email(self).deliver_now
    end

  geocoded_by :address
  after_validation :geocode

  def address
    [town,country].compact.join(', ')
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  
end

app/models/value.rb
class Value < ApplicationRecord
  has_one :type
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  has_many :products

  geocoded_by :address
  after_validation :geocode

  def address
    [city,country].compact.join(', ')
  end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'nokogiri'
  require 'open-uri'
  def index
    @product = Product.all
    # page = Nokogiri::HTML(open("https://maconscienceecolo.com/knowledge-base/100-gestes-ecolos/"))
    # n = rand(0..99)
    # @tips = page.xpath('//*[@id="kb-article-content"]/ol/li')[n].text
    if user_signed_in? && current_user.town != nil
      url = "https://api.airvisual.com/v2/nearest_city?lat=#{current_user.latitude}&lon=#{current_user.longitude}&key=BbFES4LurEehNo6PR"
      url_two ='https://api.airvisual.com/v2/city?city=Paris&state=Ile-de-France&country=France&key=BbFES4LurEehNo6PR'
      @response = open(url).read 
      current_user.latitude
      current_user.town
      @res = JSON.parse(@response).with_indifferent_access
        @aqius = @res[:data][:current][:pollution][:aqius]
        @res[:data][:current][:pollution][:mainus]
        @city = @res[:data][:city]
        @country = @res[:data][:country]
        @state = @res[:data][:state]
    end
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
    @foot_print = Footprint.where(:user_id => params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/footprints_helper.rb
module FootprintsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/methodologie_helper.rb
module MethodologieHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/admin/index.html.erb
<br>
<br>
<br>
<br>



<div class="card" >
  <div class="card-header">
    All Links
  </div>
  <ul class="list-group ">
    <li class="list-group-item"><%= link_to "products", admin_products_path %></li>
    <li class="list-group-item"><%= link_to "Users", admin_users_path %></li>
    <li class="list-group-item"><%= link_to "Foot_prints", admin_foot_prints_path %></li>
  </ul>
</div>

<br>
<h2 class="text-center">Admin Index</h2>
<div class="container">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Prenom</th>
          <th scope="col">Nom</th>
          <th scope="col">Email</th>
          <th scoe="col">Montrer</th>
          <th scoe="col">Supprimer</th>


        </tr>
      </thead>
      <tbody>
    <hr>
      <h4>Last <%= @user.count %> users</h4>
    <hr>
<% @user.each do |user| %>
        <tr>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.email %></td>
          <td><%= link_to "more" , admin_user_path(user.id) %></td>
          <td><%= link_to "Delete", admin_user_path(user.id),data: { :confirm => "Are you sure?"}, :method => :delete %></td>
        </tr>
        <tr>
        <%end%>
      </tbody>
    </table>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">Titre</th>
          <th scope="col">Resultat</th>
          <th scope="col">Montrer</th>
          <th scope="col">Supprimer</th>


        </tr>
      </thead>
      <tbody>


    <hr>
    <% if @foot_print.count == nil || @foot_print.count == 0 %>
    <p>Il n'y a pas de test</p>
      <%else%>
      <h4>Last <%= @foot_print.count %> Tests</h4>
    <% end %>
    <hr>
<% @foot_print.each do |foot| %>
        <tr>
          <td> <%= foot.product.title %> </td>
          <td><%= foot.result %></td>
          <td><%= link_to "more", admin_foot_print_path(foot) %></td>
          <td><%=link_to "Delete", admin_foot_print_path(foot), data: {:confirm => "Are you sure?"}, :method => :delete  %></td>
        </tr>
<% end %>
        <tr>
      </tbody>
    </table>
</div>